### ISSUE TITLE
Stray space at end of filename for MAINTAINERS.md

### ISSUE THREAD

**Issue by swinslow** [vmware-samples/sbom-composer#1]
Not really a functionality bug  :)  but after cloning the repo, I noticed that the filename for 'MAINTAINERS.md' appears to have an extra whitespace character at the end of the filename. This doesn't really show up in GitHub, but it should be visible when looking at the repo contents in a terminal locally.

**Comment by ivanayov** [comment]
Thank you @swinslow! Nice catch.
