### ISSUE TITLE
"compose" is not optimal as name for the executable

### ISSUE THREAD

**Issue by vargenau** [vmware-samples/sbom-composer#8]
This is not a real bug, but I do not like the name "compose" for the executable as there is already a Unix command "compose".

I would prefer something like "sbom-compose".

```
man compose

RUN-MAILCAP(1)                                         Run Mailcap Programs                                         RUN-MAILCAP(1)

NAME
       run-mailcap, view, see, edit, compose, print - execute programs via entries in the mailcap file

SYNOPSIS
       run-mailcap --action=ACTION [--option[=value]] [MIME-TYPE:[ENCODING:]]FILE [...]

       The  see, edit, compose and print versions are just aliases that default to the view, edit, compose, and print actions (re‐
       spectively).
```

**Comment by ivanayov** [comment]
Thank you for pointing out @vargenau !

What makes most sense in this case is `scompose`. Do you have any objections or another proposal?

**Comment by vargenau** [comment]
I would prefer "sbom-compose" or "sbomcompose" that is more explicit.
Or "spdx-compose", "spdxcompose".

**Comment by ivanayov** [comment]
Addressed in [Change compose command](https://github.com/vmware-samples/sbom-composer/commit/4c8f1ec151e4ec7d31b643a1b381427ef583d071)
